# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Evan Shortiss
email: evanshortiss@gmail.com
description: Evan Shortiss is a software developer who's passionate about developer and user experience. He spends his days hacking on OpenShift/Kubernetes, Mobile, Web, Kafka, and more at Red Hat. He spends his nights pretending to be a pro FPS player.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evanshortiss.com" # the base hostname & protocol for your site
twitter_username: evanshortiss
github_username:  evanshortiss
encoding: utf-8
permalink: /:title

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - octopress-autoprefixer
  - jekyll-redirect-from
