# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Evan Shortiss
email: evanshortiss@gmail.com
description: I'm Evan, a Software Engineer working at FeedHenry by Red Hat. I like to write code, write about code, take photographs, and play video games when life allows.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://evanshortiss.com" # the base hostname & protocol for your site
twitter_username: evanshortiss
github_username:  evanshortiss

# Build settings
markdown: kramdown

analytics :
  provider : google
  google :
      tracking_id : 'UA-75946220-2'
  getclicky :
    site_id :
